// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fansbktmwnskvolllfhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbnNia3Rtd25za3ZvbGxsZmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Mzc4OTUsImV4cCI6MjA1ODExMzg5NX0.OD5HxfjuRU0KcAnnbJgZLIU6dqBHqktBWrOE95vDjHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);